#!/bin/sh -e

autoreconf --install

libdir() {
	( cd $1/$(gcc -print-multi-os-directory); pwd )
}

args="--prefix=/usr \
--sysconfdir=/etc \
--libdir=$(libdir /usr/lib)"

hackargs="--enable-debug"

cat <<EOC

----------------------------------------------------------------
Initialized build system. For a common configuration please run:
----------------------------------------------------------------

./configure CFLAGS='-g -O2' $args

If you are debugging or hacking on Policy Daemon, consider
configuring like below:

./configure CFLAGS="-g -O2 -Werror" $args $hackargs

EOC

